import { ArrowRight, AudioLines, FileText, Github, Globe2, MessagesSquare, Server, Sparkles, TerminalSquare } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect } from 'react';
import { PublicFooter, PublicHeader } from './PublicShell';
import { ProductWorkspacePreview } from './ProductWorkspacePreview';
import { DAEMON_START_COMMAND, GITHUB_URL, INSTALL_COMMAND, LOGIN_COMMAND } from './publicContent';
import './public.css';

const features = [
  { icon: MessagesSquare, title: 'Conversation when it helps', text: 'Read messages, tools, diffs, and permissions in a calm structured view instead of a phone-sized transcript.' },
  { icon: TerminalSquare, title: 'The terminal when it matters', text: 'Drop into a durable tmux terminal, then return a mirrored Claude session to structured conversation.' },
  { icon: FileText, title: 'The work around the agent', text: 'Browse and preview files, keep notes, and move tasks without reconstructing the context somewhere else.' },
  { icon: AudioLines, title: 'A coordinator you can talk to', text: 'Dispatch background work with a Claude-powered meta-agent; optional voice is available when a voice service is configured.' },
];

function ProductShowcase() {
  return <section className="pub-product" aria-labelledby="product-title">
    <div className="pub-product-intro"><div><div className="eyebrow">THE REAL PRODUCT UI</div><h2 id="product-title">One thread. Three ways to stay in it.</h2></div><p>Built from the authenticated app's production component styles and Console tokens, rendered with sanitized example data.</p></div>
    <ProductWorkspacePreview />
    <div className="pub-product-caption mono"><span>PRODUCTION VISUAL CONTRACTS · SANITIZED DATA</span><span>RESPONSIVE WEB · NO DESKTOP HANDOFF REQUIRED</span></div>
  </section>;
}

export function LandingScreen() {
  useEffect(() => { document.title = 'Very Happy — Work anywhere. Keep the thread.'; }, []);
  return <div className="pub-page"><PublicHeader /><main id="main-content">
    <section className="pub-hero" aria-labelledby="hero-title"><div className="pub-hero-copy"><div className="eyebrow">OPEN AGENT WORKSPACE // YOUR MACHINES</div><h1 id="hero-title">Work anywhere.<br /><span>Keep the thread.</span></h1><p>Run coding agents on your machines. Follow the conversation, terminal, files, and tasks from any screen—without carrying the whole system in your head.</p><div className="pub-actions"><a className="pub-button is-primary" href={`${import.meta.env.BASE_URL}signup`}>Connect a machine <ArrowRight size={16} /></a><Link className="pub-button" to="/docs/quickstart">See how it works</Link></div><div className="pub-meta mono"><span>Claude + Codex</span><span>ACP extensible</span><span>self-hostable</span></div></div><aside className="pub-hero-thesis"><span className="mono">THE PROMISE</span><p>The agent keeps working there.</p><p>You keep moving here.</p><div><i /> one continuous thread</div></aside></section>
    <ProductShowcase />
    <section className="pub-agents" aria-labelledby="agents-title"><div className="pub-section-head"><div><div className="eyebrow">AGENTS, NOT A WALLED GARDEN</div><h2 id="agents-title">Bring the agent that fits the work.</h2></div><p>The workspace follows your work instead of forcing every task through one vendor.</p></div><div className="pub-agent-grid"><article><div className="pub-status mono">DEEP SUPPORT</div><h3>Claude Code</h3><p>Structured conversation, tool and permission views, terminal mirroring, files, usage, and resume.</p></article><article><div className="pub-status mono">AVAILABLE NOW</div><h3>Codex</h3><p>Start and resume Codex through the same CLI, trusted relay, responsive workspace, and machine fleet.</p></article><article><div className="pub-status mono">EXTENSIBLE NOW</div><h3>ACP agents</h3><p>Gemini ships as an ACP mode; the generic runner connects compatible commands such as OpenCode.</p></article><article className="is-roadmap"><div className="pub-status mono">ROADMAP</div><h3>Pi + provider gateway</h3><p>Cross-provider subtask dispatch and a coordinator that routes work to the best available agent.</p></article></div></section>
    <section className="pub-flow" aria-labelledby="flow-title"><div className="eyebrow">FIRST CONNECTION</div><h2 id="flow-title">From zero to a live agent in four steps.</h2><ol><li><span>01</span><div><h3>Create an account</h3><p>Use Google or username and password on your chosen relay.</p></div></li><li><span>02</span><div><h3>Install the CLI</h3><code>{INSTALL_COMMAND}</code></div></li><li><span>03</span><div><h3>Connect the machine</h3><code>{LOGIN_COMMAND}{'\n'}{DAEMON_START_COMMAND}</code></div></li><li><span>04</span><div><h3>Choose an agent</h3><p>Run <code>very-happy</code>, <code>very-happy codex</code>, or start from Web.</p></div></li></ol></section>
    <section className="pub-trust" aria-labelledby="trust-title"><div><div className="eyebrow">TRUST MODEL</div><h2 id="trust-title">A relay you can reason about.</h2></div><p>Very Happy is <strong>server-trusted, not end-to-end encrypted</strong>. A relay operator—or anyone who compromises it—may access relayed content, account recovery material, and capabilities exposed by an online daemon. Use the community service if you trust its operator; self-host when you need to own that boundary.</p><Link to="/docs/security">Read the security model <ArrowRight size={15} /></Link></section>
    <section className="pub-choices" aria-labelledby="deploy-title"><div className="pub-section-head"><div><div className="eyebrow">DEPLOYMENT</div><h2 id="deploy-title">Choose who operates the relay.</h2></div></div><div className="pub-choice-grid"><article><Globe2 size={22} /><h3>Very Happy Cloud</h3><p>The quickest start. Community-operated, capacity-limited, and provided without an uptime SLA.</p><Link to="/docs/cloud">Cloud guide <ArrowRight size={14} /></Link></article><article><Server size={22} /><h3>Self-hosted</h3><p>Your access policy, storage, backups, and operator boundary. Still server-trusted by design.</p><Link to="/docs/self-hosting">Self-hosting guide <ArrowRight size={14} /></Link></article></div></section>
    <section className="pub-manifesto" aria-labelledby="manifesto-title"><div className="eyebrow">WHY VERY HAPPY</div><h2 id="manifesto-title">The interface carries the overhead.<br /><span>You get to be Very Happy.</span></h2><p>Fewer tabs to patrol, less context to rebuild, and more attention left for the decisions only you can make.</p><div className="pub-manifesto-line mono"><span>LESS BABYSITTING</span><span>LESS CONTEXT REBUILDING</span><span>MORE WORK IN MOTION</span></div></section>
    <section className="pub-section" aria-labelledby="features-title"><div className="pub-section-head"><div><div className="eyebrow">MORE THAN REMOTE CONTROL</div><h2 id="features-title">Use the right interface for the moment.</h2></div><p>A remote shell returns you to a cursor. Very Happy returns you to the decision.</p></div><div className="pub-feature-grid">{features.map(({ icon: Icon, title, text }) => <article key={title}><Icon size={20} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="pub-orchestration" aria-labelledby="orchestration-title"><div><div className="eyebrow">FROM TOOL TO WORK SYSTEM</div><h2 id="orchestration-title">Let agents move the work. Step in for judgment.</h2><p>Notes, tasks, voice, webhooks, and local adapters already surround the core workspace. The direction is a provider-neutral gateway and a visible multi-agent office—not more buttons around a terminal.</p><Link to="/docs/integrations">Explore integrations <ArrowRight size={15} /></Link></div><div className="pub-orbit" aria-label="Agent orchestration model"><span className="pub-orbit-center"><Sparkles size={18} /> coordinator</span><span>Claude</span><span>Codex</span><span>ACP</span><span>voice</span><span>tasks</span></div></section>
    <section className="pub-final"><div><div className="eyebrow">WORK ANYWHERE</div><h2>Keep the machine. Lose the overhead.</h2><p>Open source, self-hostable, and built from a heavily modified slopus/happy foundation.</p></div><div className="pub-actions"><a className="pub-button is-primary" href={`${import.meta.env.BASE_URL}signup`}>Get started <ArrowRight size={16} /></a><a className="pub-button" href={GITHUB_URL}><Github size={16} /> View source</a></div></section>
  </main><PublicFooter /></div>;
}
