import { ArrowRight, Github, Globe2, Laptop, Server, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect } from 'react';
import { PublicFooter, PublicHeader } from './PublicShell';
import { CoreFeatureProofs } from './CoreFeatureProofs';
import { ProductWorkspacePreview } from './ProductWorkspacePreview';
import { DAEMON_START_COMMAND, GITHUB_URL, INSTALL_COMMAND, LOGIN_COMMAND } from './publicContent';
import './public.css';

function ProductShowcase() {
  return <section className="pub-product" aria-labelledby="product-title">
    <div className="pub-product-intro"><div><div className="eyebrow">THE REAL PRODUCT UI</div><h2 id="product-title">One workspace. Three levels of attention.</h2></div><p>After you explicitly install the optional Claude terminal hooks, the terminal and structured view can follow the same hand-started Claude process; the board steps back across your work. All three reuse production visual contracts with sanitized data.</p></div>
    <div className="pub-product-frame"><div className="pub-product-frame-head mono"><span><i /> LIVE PRODUCT SURFACE</span><span>WORKSTATION · SANITIZED SESSION</span></div><ProductWorkspacePreview /></div>
    <div className="pub-product-caption mono"><span>PRODUCTION VISUAL CONTRACTS · SANITIZED DATA</span><span>RESPONSIVE WEB · NO DESKTOP HANDOFF REQUIRED</span></div>
  </section>;
}

function HeroProductStage() {
  return <aside className="pub-hero-product" aria-label="Interactive preview of the real Very Happy product interface">
    <div className="pub-hero-product-head mono"><span><i /> SANITIZED DEMO · LIVE PRODUCT UI</span><span>WORKSPACE CONTINUITY</span></div>
    <ProductWorkspacePreview compact />
    <div className="pub-hero-product-foot mono"><span>PROCESS RUNS THERE</span><span>CONTEXT ARRIVES HERE</span></div>
  </aside>;
}

export function LandingScreen() {
  useEffect(() => { document.title = 'Very Happy — Work anywhere. Keep the thread.'; }, []);
  return <div className="pub-page"><PublicHeader /><main id="main-content">
    <section className="pub-hero" aria-labelledby="hero-title"><div className="pub-hero-copy"><div className="eyebrow">OPEN AGENT WORKSPACE // YOUR MACHINES</div><h1 id="hero-title">Work anywhere.<br /><span>Keep the thread.</span></h1><p>Run coding agents on your machines. Follow the conversation, terminal, files, and tasks from any screen—without carrying the whole system in your head.</p><div className="pub-actions"><a className="pub-button is-primary" href={`${import.meta.env.BASE_URL}signup`}>Connect a machine <ArrowRight size={16} /></a><Link className="pub-button" to="/docs/quickstart">See how it works</Link></div><div className="pub-meta mono"><span>Claude + Codex</span><span>Gemini + OpenCode via ACP · beta</span><span>self-hostable</span></div></div><HeroProductStage /></section>
    <ProductShowcase />
    <section className="pub-agents" aria-labelledby="agents-title"><div className="pub-section-head"><div><div className="eyebrow">AGENTS, NOT A WALLED GARDEN</div><h2 id="agents-title">Bring the agent that fits the work.</h2></div><p>The workspace follows your work instead of forcing every task through one vendor.</p></div><div className="pub-agent-grid"><article><div className="pub-status mono">DEEP SUPPORT</div><h3>Claude Code</h3><p>Structured SDK conversations work directly. Mirroring hand-started Claude inside a Very Happy terminal requires the optional terminal hooks.</p></article><article><div className="pub-status mono">AVAILABLE NOW</div><h3>Codex</h3><p>Start and resume Codex on a connected machine through the same CLI, trusted relay, and responsive terminal workspace.</p></article><article><div className="pub-status mono">BETA · IMPLEMENTED</div><h3>Gemini + OpenCode via ACP</h3><p>The CLI ships an Agent Client Protocol backend and generic runner. The agent command must expose a compatible ACP stdio endpoint.</p></article><article className="is-roadmap"><div className="pub-status mono">ROADMAP</div><h3>Pi + provider gateway</h3><p>Cross-provider subtask dispatch and a coordinator that routes work to the best available agent.</p></article></div></section>
    <section className="pub-flow" aria-labelledby="flow-title"><div className="eyebrow">FIRST CONNECTION</div><h2 id="flow-title">From zero to a live agent in four steps.</h2><ol><li><span>01</span><div><h3>Create an account</h3><p>Use Google or username and password on your chosen relay.</p></div></li><li><span>02</span><div><h3>Install the CLI</h3><code>{INSTALL_COMMAND}</code></div></li><li><span>03</span><div><h3>Connect the machine</h3><code>{LOGIN_COMMAND}{'\n'}{DAEMON_START_COMMAND}</code></div></li><li><span>04</span><div><h3>Choose an agent</h3><code>{'very-happy\nvery-happy codex'}</code><p>Or start a session from Web.</p></div></li></ol></section>
    <section className="pub-trust" aria-labelledby="trust-title"><div><div className="eyebrow">TRUST MODEL</div><h2 id="trust-title">A relay you can reason about.</h2></div><p>Very Happy is <strong>server-trusted, not end-to-end encrypted</strong>. A relay operator—or anyone who compromises it—may access relayed content, account recovery material, and capabilities exposed by an online daemon. Use the community service if you trust its operator; self-host when you need to own that boundary.</p><Link to="/docs/security">Read the security model <ArrowRight size={15} /></Link></section>
    <section className="pub-choices" aria-labelledby="deploy-title"><div className="pub-section-head"><div><div className="eyebrow">DEPLOYMENT</div><h2 id="deploy-title">Choose who operates the relay.</h2></div></div><div className="pub-choice-grid"><article><Globe2 size={22} /><h3>Very Happy Cloud</h3><p>The quickest start. Community-operated, capacity-limited, and provided without an uptime SLA.</p><Link to="/docs/cloud">Cloud guide <ArrowRight size={14} /></Link></article><article><Server size={22} /><h3>Self-hosted</h3><p>Your access policy, storage, backups, and operator boundary. Still server-trusted by design.</p><Link to="/docs/self-hosting">Self-hosting guide <ArrowRight size={14} /></Link></article></div></section>
    <section className="pub-manifesto" aria-labelledby="manifesto-title"><div className="eyebrow">WHY VERY HAPPY</div><h2 id="manifesto-title">The interface carries the overhead.<br /><span>You get to be Very Happy.</span></h2><p>Fewer tabs to patrol, less context to rebuild, and more attention left for the decisions only you can make.</p><div className="pub-manifesto-line mono"><span>LESS BABYSITTING</span><span>LESS CONTEXT REBUILDING</span><span>MORE WORK IN MOTION</span></div></section>
    <CoreFeatureProofs />
    <section className="pub-orchestration" aria-labelledby="orchestration-title"><div><div className="eyebrow">FROM TOOL TO WORK SYSTEM</div><h2 id="orchestration-title">Keep agents moving. Step in for judgment.</h2><p>Notes, tasks, voice, webhooks, and local adapters already surround the core workspace. Today you choose the machine and agent; provider-neutral routing and a visible multi-agent office are roadmap.</p><Link to="/docs/integrations">Explore integrations <ArrowRight size={15} /></Link></div><div className="pub-fleet" aria-label="Sanitized account overview with three connected machines"><div className="pub-fleet-head mono"><span>ACCOUNT OVERVIEW / SANITIZED</span><span><i /> 3 CONNECTIONS</span></div><div className="pub-fleet-row"><span><Server size={15} /> build-server</span><strong>Codex · running tests</strong><small className="mono">02:18</small></div><div className="pub-fleet-row"><span><Laptop size={15} /> workstation</span><strong>Claude · awaiting review</strong><small className="mono">00:42</small></div><div className="pub-fleet-row"><span><Server size={15} /> staging</span><strong>terminal · healthy</strong><small className="mono">DEMO</small></div><div className="pub-fleet-foot mono"><Sparkles size={14} /> ONE ACCOUNT VIEW · YOU CHOOSE WHERE WORK RUNS</div></div></section>
    <section className="pub-final"><div><div className="eyebrow">WORK ANYWHERE</div><h2>Keep the machine. Lose the overhead.</h2><p>Open source, self-hostable, and built from a heavily modified slopus/happy foundation.</p></div><div className="pub-actions"><a className="pub-button is-primary" href={`${import.meta.env.BASE_URL}signup`}>Get started <ArrowRight size={16} /></a><a className="pub-button" href={GITHUB_URL}><Github size={16} /> View source</a></div></section>
  </main><PublicFooter /></div>;
}
