export const messageActionsCopy = (lang: string) => lang.startsWith('zh') ? {
    sourceChanged: '原会话已变化，请关闭后重新编辑。', branchContext: '从历史消息创建的分支',
    choose: '选择要编辑的原消息', chooseHint: '这条消息尚未关联可靠的回退标识。请从机器上的实际历史中选择原消息，不会自动按文字猜测。', loading: '正在读取历史…', empty: '未找到可编辑的历史消息。',
    actions: '消息操作', quote: '引用', edit: '编辑', cancel: '取消', submit: '在新分支中发送',
    title: '编辑这条消息', text: '新的消息', busy: '正在创建分支…', open: '打开新分支', parent: '返回原会话',
    description: '从这条消息之前的历史创建新分支，原会话保留。已执行的命令和文件修改不会撤销。',
    unsupported: '此会话暂不支持精确回退。可以引用消息继续讨论。',
    missingPoint: '这条历史消息缺少回退标识，无法安全编辑重跑。',
    attachments: '带附件的消息暂不支持编辑重跑，请在新消息中重新附加文件。',
    pending: '这条消息尚未执行，或已取消。排队消息请在输入区编辑。',
    running: '请先停止当前运行，再编辑重跑。',
    failed: '未完成重跑。创建结果可能尚未同步，请先检查会话列表，不要重复创建。',
    oldDaemon: '这台机器尚不支持编辑重跑，请先更新 CLI 并启动 daemon。',
    queued: '已创建分支并加入发送队列',
    sendFailed: '新分支已创建，消息尚未加入发送队列。打开新分支继续编辑并发送。',
} : {
    sourceChanged: 'The original session changed. Close and reopen the editor.', branchContext: 'Branched from an earlier message',
    choose: 'Choose the original message', chooseHint: 'This message has no reliable rewind mapping. Select the original from the machine’s actual history; no text matching is used.', loading: 'Reading history…', empty: 'No editable history found.',
    actions: 'Message actions', quote: 'Quote', edit: 'Edit', cancel: 'Cancel', submit: 'Send in new branch',
    title: 'Edit this message', text: 'New message', busy: 'Creating branch…', open: 'Open new branch', parent: 'Back to original session',
    description: 'Start a new branch from before this message. The original conversation is kept. Commands and file changes are not undone.',
    unsupported: 'This session does not support exact rewind yet. Quote the message to continue discussing it.',
    missingPoint: 'This message has no reliable rewind identifier and cannot be safely edited.',
    attachments: 'Editing messages with attachments is not supported yet. Attach the files again in a new message.',
    pending: 'This message has not run or was canceled. Edit queued messages in the composer.',
    running: 'Stop the current run before editing and rerunning.',
    failed: 'Rerun did not finish. Creation may still be syncing; check the session list before creating again.',
    oldDaemon: 'Update the CLI and start the daemon on this machine to enable edit and rerun.',
    queued: 'Branch created and message queued',
    sendFailed: 'The branch was created, but the message was not queued. Open the branch to edit and send it.',
};
