import { useState } from 'react';
import { ChevronRight, FileText, Folder, Search } from 'lucide-react';
export const creationChoices = ['普通对话', '高级配置对话', '终端会话', '指定目录终端', '接入已有 tmux', '导入 Claude 历史', '连接新机器'];
export const reviewActions = ['新建', '文件浏览器', '快捷笔记', '全部笔记', '用这个对话组建团队', '团队', '待办', '运行概览', '快捷指令', '剪贴板历史', '快捷键', '设置', '帮助'];
export function WorkspaceReviewPanels({ panel, open, newChat, openSession, note, setNote }: {panel:string;open:(p:string)=>void;newChat:()=>void;openSession:()=>void;note:string;setNote:(v:string)=>void}) {
 const [query,setQuery]=useState(''); const [file,setFile]=useState('');
 if(panel==='新建') return <><p className="wd-muted">在同一个入口选择会话类型。终端与普通对话并列，接入已有会话不新建 tmux。</p>{creationChoices.map(choice=><button className="wd-option" key={choice} onClick={()=>choice==='普通对话'?newChat():open(choice)}>{choice}<ChevronRight size={14}/></button>)}</>;
 if(panel==='命令中心') return <><label className="wd-search"><Search size={14}/><input autoFocus aria-label="搜索命令或会话" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索命令或会话…"/></label>{[...reviewActions,'会话：统一会话界面与输入体验'].filter(x=>x.toLowerCase().includes(query.toLowerCase())).map(action=><button className="wd-option" key={action} onClick={()=>action.startsWith('会话：')?openSession():open(action)}>{action}<ChevronRight size={14}/></button>)}</>;
 if(panel==='快捷笔记'||panel==='全部笔记') return <><p className="wd-muted">本地示例笔记 · ⌘J / Ctrl+J · 正式版保留笔记列表与同步</p><textarea className="wd-note-editor" aria-label="快捷笔记内容" value={note} onChange={e=>setNote(e.target.value)} placeholder="随手记下下一步…"/><button className="wd-option" onClick={()=>open(panel==='快捷笔记'?'全部笔记':'快捷笔记')}>{panel==='快捷笔记'?'查看全部笔记':'返回快捷笔记'}<ChevronRight size={14}/></button></>;
 if(panel==='文件浏览器') return <><p className="wd-muted">示例工作区 /very-happy · 文件 / 改动入口</p><button className="wd-option" onClick={()=>setFile('修改预览：统一间距与输入区样式。')}><Folder size={14}/>当前改动<ChevronRight size={14}/></button>{['src/screens/session/input.css','src/screens/sessions/Sidebar.tsx','docs/design-language.md'].map(name=><button className="wd-option" key={name} onClick={()=>setFile(name+'\n\n/* 本地示例文件，正式版读取会话工作区。 */')}><FileText size={14}/><span style={{overflowWrap:'anywhere'}}>{name}</span></button>)}{file&&<pre className="wd-file-example">{file}</pre>}</>;
 if(panel==='快捷键') return <><p className="wd-muted">保留现有语义；不是把全部快捷键重新定义一遍。</p>{['⌘K / Ctrl+K：命令中心','⌘J / Ctrl+J：快捷笔记','⌘. / Ctrl+.：快捷指令；菜单内 1–9 选择','⌘N（PWA）/ ⌥N：新终端，仍保留快速路径','⌘1–9 / Ctrl+1–9：切换会话','⌘R / Ctrl+R：重命名当前会话','⌘W（PWA）/ ⌥W：关闭或归档当前会话','⌘[ / Alt+←：返回'].map(text=><p className="wd-muted" key={text}>{text}</p>)}<p className="wd-muted">原型演示 K、J、.；其余在真实组件接入时回归，避免拦截浏览器或操作真实会话。</p></>;
 if(panel==='运行概览') return <><p className="wd-muted">原任务看板的独立价值：跨会话与终端的待处理、运行状态和最近完成记录。先移出常驻导航，不删除数据。</p>{['待确认 · 终端权限（示例）','运行中 · 检查移动布局（示例）','最近完成 · 类型检查（示例）'].map(text=><div className="wd-option" key={text}>{text}</div>)}</>;
 if(panel==='用这个对话组建团队') return <><p className="wd-muted">以当前对话接续团队目标。正式版仅在会话支持 teams-adopt-v1、未归档且未归属团队时展示。</p><div className="wd-option">来源：统一会话界面与输入体验</div><div className="wd-option">目标：完成工作台体验改版</div><button className="wd-option" onClick={()=>open('团队')}>预览团队工作区<ChevronRight size={14}/></button></>;
 if(creationChoices.includes(panel)) return <><p className="wd-muted">{panel} · 配置入口预览，不会启动真实进程。</p><div className="wd-option">机器：mac-office（示例）</div>{panel==='接入已有 tmux'?<><div className="wd-option">选择已有会话：work / review（示例）</div><p className="wd-muted">接入、关闭视图与结束远端 tmux 是不同操作，保留独立语义。</p></>:<div className="wd-option">目录：/very-happy（示例）</div>}<button className="wd-option" onClick={()=>open('新建')}>返回类型选择</button></>;
 return <p className="wd-muted">{panel}入口已纳入迁移清单。此处尚未接入真实数据。</p>;
}
