export const MAX_CHAT_ATTACHMENT_SOURCE_BYTES = 50 * 1024 * 1024;
export const CHAT_ATTACHMENT_ENCRYPTION_OVERHEAD_BYTES = 40;
export const MAX_CHAT_ATTACHMENT_ENCRYPTED_BYTES =
    MAX_CHAT_ATTACHMENT_SOURCE_BYTES + CHAT_ATTACHMENT_ENCRYPTION_OVERHEAD_BYTES;
